spring:
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/users/**, /gateway/users/**
        - id: post-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/post/**, /api/comment/**, /api/group/**, /gateway/group/**
        - id: notices-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/notices/**
        - id: search-service
          uri: http://localhost:8004
          predicates:
            - Path=/api/search/**
        - id: file-service
          uri: http://localhost:8005
          predicates:
            - Path=/api/file/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:5173" # 필요에 따라 설정
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTION
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: # 커스텀 헤더
              - Location
              - X-Needs-Refresh
              - X-GATE-WAY-KEY
        add-to-simple-url-handler-mapping: true
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
jwt:
  refresh-token: ZHNrbGZqYWRrbHNmamxrZHNhZmtqbGFzZGZsaztqemxrY3h2anpjdnBvY2l4emp2ODlwajMyNDk4ZkAkQCFAJGZkZ3N6ZHNhZmFkc2Y=
  access-token: SGVsbG9AI2UzV3JvbGQhQCN9RHxkc2prZC0oOTBNeVNlY3JldCEyMyRGREcjMw==