spring:
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**, /api/follow/**, /gateway/users/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/post/**, /api/comment/**, /api/group/**, /gateway/group/**
        - id: notices-service
          uri: lb://NOTICES-SERVICE
          predicates:
            - Path=/api/notices/**
        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/api/search/**
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/api/file/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:5173" # 필요에 따라 설정
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTION
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: # 커스텀 헤더
              - Location
              - X-Needs-Refresh
              - X-GATE-WAY-KEY
        add-to-simple-url-handler-mapping: true
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 120
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
      base-path: /actuator
  endpoint:
    info:
      access: read_only
    health:
      show-details: always
logging:
  level:
    root: INFO
    org.springframework.cloud.config: WARN
    org.springframework.boot: WARN
    kyulab.gatewayserver.filter: DEBUG
jwt:
  refresh-token: ZHNrbGZqYWRrbHNmamxrZHNhZmtqbGFzZGZsaztqemxrY3h2anpjdnBvY2l4emp2ODlwajMyNDk4ZkAkQCFAJGZkZ3N6ZHNhZmFkc2Y=
  access-token: SGVsbG9AI2UzV3JvbGQhQCN9RHxkc2prZC0oOTBNeVNlY3JldCEyMyRGREcjMw==